//src/mentList.js
export const exampleMentList = [
  { id: 1, name: ' ', content: '레아야 사랑해' },
  { id: 2, name: ' ', content: '앞으로도 함께야' },
  { id: 3, name: ' ', content: '항상 응원해' },
  { id: 4, name: ' ', content: '레아찬양!레아응원!레아사랑!레아최고!' },
  { id: 5, name: ' ', content: 'au에서도 항상 응원할게' },
  { id: 6, name: ' ', content: '레아를 알게되서 너무 행복해' },
    { id: 7, name: ' ', content: '앞으로도 좋은 라이브 잘 부탁합니다' },
  { id: 8, name: ' ', content: '레아짱!레아짱!레아짱!레아짱!레아짱!' },
  { id: 9, name: ' ', content: '고마워요' },
  { id: 10, name: ' ', content: '레아 최고!!!!!!' },
  { id: 11, name: ' ', content: '아모레로써도 au로써도 에쿠레아로써도 항상 멋있는 라이브를 보여줘서 고마워 사랑해' },
  { id: 12, name: ' ', content: '덕분에 행복했어 앞으로도 행복하자' },
    { id: 13, name: ' ', content: '레아야 사랑해' },
  { id: 14, name: ' ', content: '앞으로도 함께야' },
  { id: 15, name: ' ', content: '항상 응원해' },
  { id: 16, name: ' ', content: '레아찬양!레아응원!레아사랑!레아최고!' },
  { id: 17, name: ' ', content: 'au에서도 항상 응원할게' },
  { id: 18, name: ' ', content: '레아를 알게되서 너무 행복해' },
    { id: 19, name: ' ', content: '앞으로도 좋은 라이브 잘 부탁합니다' },
  { id: 20, name: ' ', content: '레아짱!레아짱!레아짱!레아짱!레아짱!' },
  { id: 21, name: ' ', content: '고마워요' },
  { id: 22, name: ' ', content: '레아 최고!!!!!!' },
  { id: 23, name: ' ', content: '아모레로써도 au로써도 에쿠레아로써도 항상 멋있는 라이브를 보여줘서 고마워 사랑해' },
  { id: 24, name: ' ', content: '덕분에 행복했어 앞으로도 행복하자' },
    { id: 25, name: ' ', content: '레아짱!레아짱!레아짱!레아짱!레아짱!' },
  { id: 26, name: ' ', content: '고마워요' },
  { id: 27, name: ' ', content: '레아 최고!!!!!!' },
  { id: 28, name: ' ', content: '아모레로써도 au로써도 에쿠레아로써도 항상 멋있는 라이브를 보여줘서 고마워 사랑해' },
  { id: 29, name: ' ', content: '덕분에 행복했어 앞으로도 행복하자' },
];

// export const exampleMentList = [
// "문장1",
// "문장2",
// "문장3",
// "문장4",
// "문장5",
// "문장6"
// ];